auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 香江望百川
url: https://simon126649.github.io/
feed: /atom.xml
author_info: <a href="https://simon126649.github.io/"香江望百川</a>
